### ISSUE TITLE
Tests against all `Array`/`AbstractArray` APIs 

### ISSUE THREAD

**Issue by yebai** [withbayes/Taped.jl#27]
We should consider testing against all `stdlib` functions for Julia's `Array` type. A more comprehensive test should also include `PDMats` and `Statistics`. 

See e.g. [`Tracker` tests](https://github.com/FluxML/Tracker.jl/blob/master/test/tracker.jl ) for an example.

**Comment by willtebbutt** [comment]
I see.

A pretty good way to construct a _very_ thorough test set is to just look at the results of
```julia
methodswith(Array, Base; supertypes=true)
methodswith(Vector, Base; supertypes=true)
methodswith(Array, LinearAlgebra; supertypes=true)
methodswith(Vector, LinearAlgebra; supertypes=true)
```

**Comment by willtebbutt** [comment]
Closing in favour of #31
